### ISSUE TITLE
Natural gas implementation

### ISSUE THREAD

**Issue by mg-nz** [brunsy/ha-frankenergy#1]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/brunsy/ha-managemyhealth/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

There is a slight issue due to the way that the Frank Energy backend handles accounts with multiple services (e.g. electricity and natural gas). These appear as 2 different billing accounts under the one user account, and viewing information within the mobile app requires switching between the two accounts. If the mobile app is closed with the natural gas account selected then this integration fails to retrieve electricity usage.

### Describe the solution you'd like

Step 1 would be to be able to fetch natural gas usage (having selected this within the mobile app). Unfortunately this does not appear to be as simple as modifying the API call address from "../electricity/..." to ".../natural-gas/...." (or naturalgas or gas). Viewing the API calls for the browser-based user control panel shows the API address and parameters are quite different between the two types of accounts (and furthermore different from the mobile ones).
Step 2 would be for the integration to be able to actively select the correct account (e.g. first choose the electricity account and retrieve electricity usage, then select the natural gas account and retrieve the natural gas usage). 

### Describe alternatives you've considered

The only alternative I've looked at would be to manually download usage data and upload it to HA, but this is time-consuming and there doesn't seem be to inherent support for adding data in this way in HA.

### Additional context

-

**Comment by brunsy** [comment]
Sorry, haven't had time to look into this and I don't have Gas on my account.

I'm happy to add it in, although to do this I'll need the gas endpoints and response structure from someone. Do you have the android app? 
If so I can run you through the steps to MITM them, otherwise your best bet is to try and figure them out from the web.

**Comment by mg-nz** [comment]
Work's been way too busy to get into this again, but FYI I've just received an email from Frank saying that they're going to stop providing natural gas from March 2025, so it's probably not worth thinking about anymore!
